apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
      - name: minecraft-pv-storage
        persistentVolumeClaim:
          claimName: minecraft-data-claim
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "latest"
        - name: MOTD
          value: "A minecraft server named \u00a76\u00a7lLP A2SR\u00a7r\\nThe server is running under \u00a79\u00a7l\u00a7oKubernetes"
        - name: MAX_PLAYERS
          value: "18"
        - name: MEMORY
          value: "4G"
        - name: OPS
          value: "WolfAnto"
        volumeMounts:
          - mountPath: "/data"
            name: minecraft-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
  type: LoadBalancer
