apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "latest"
        - name: MOTD
          value: "A minecraft server named \u00a76\u00a7lLP A2SR\u00a7r\\nThe server is running under \u00a79\u00a7l\u00a7oKubernetes"
          #value: "\u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e- \u00A76\u00A7lLP A2SR \u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e-\u00A76*\u00A7e-           \u00A7r\n\u00A76\u00A7l|  \u00A7e Chill  \u00A76\u00A7l| \u00A7e  Survie    \u00A76\u00A7l|  \u00A7e18 Slots \u00A76\u00A7l|"
        - name: MAX_PLAYERS
          value: "18"
        - name: MEMORY
          value: "4G"

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
spec:
  selector:
    app: minecraft
  ports:
  - name: minecraft
    port: 25565
    targetPort: 25565
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
