apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  selector:
    matchLabels:
      app: tetris
  replicas: 1
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - name: tetris
        image: m0n01/tetris:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tetris
spec:
  selector:
    app: tetris
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: LoadBalancer
